spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
  thymeleaf:
    cache: false
jwt:
  privateKey: 1234567812345678
server:
  port: 8081
mongo:
  base:
    distribute:
      test1: aaa
    test: bbb
